import { PersistedAppData } from "@/lib/types";

function shiftDate(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
}

export function createDemoState(): PersistedAppData {
  return {
    activeTab: "dashboard",
    mode: "landlord",
    selectedContactId: "contact-dana",
    lastPushAt: null,
    user: {
      name: "Morgan Park",
      email: "demo@landlordforge.com",
      tier: "free",
      isAuthenticated: false,
    },
    properties: [
      {
        id: "property-maple",
        address: "1421 Maple Street, Unit 2",
        tenantName: "Dana Cole",
        rentAmount: 1650,
        dueDay: 1,
        note: "Lease renews in August.",
      },
      {
        id: "property-cedar",
        address: "77 Cedar Avenue",
        tenantName: "Evan Ross",
        rentAmount: 1895,
        dueDay: 5,
        note: "Garage keypad recently reset.",
      },
    ],
    jobs: [
      {
        id: "job-hvac",
        clientName: "Summit Dental",
        description: "HVAC spring service and thermostat swap",
        amount: 920,
        dueDate: shiftDate(6),
        note: "Waiting on rooftop access window.",
      },
      {
        id: "job-kitchen",
        clientName: "Hartwell Design",
        description: "Punch-list carpentry for kitchen remodel",
        amount: 1450,
        dueDate: shiftDate(10),
        note: "Last walkthrough booked for Thursday.",
      },
    ],
    contacts: [
      {
        id: "contact-dana",
        linkedRecordId: "property-maple",
        kind: "tenant",
        displayName: "Dana Cole",
        email: "dana@tenantmail.com",
        phone: "(555) 220-1930",
        label: "Maple Street lease",
        notes: "Prefers text before visits. Paid on time for six straight months.",
        paymentHistory: [
          {
            id: "hist-dana-1",
            date: shiftDate(-32),
            amount: 1650,
            status: "paid",
            note: "March rent received via ACH.",
          },
          {
            id: "hist-dana-2",
            date: shiftDate(-3),
            amount: 1650,
            status: "overdue",
            note: "April rent still outstanding.",
          },
        ],
      },
      {
        id: "contact-evan",
        linkedRecordId: "property-cedar",
        kind: "tenant",
        displayName: "Evan Ross",
        email: "evan@tenantmail.com",
        phone: "(555) 867-1192",
        label: "Cedar Avenue tenant",
        notes: "Auto-pay enabled. Dog on site.",
        paymentHistory: [
          {
            id: "hist-evan-1",
            date: shiftDate(-28),
            amount: 1895,
            status: "paid",
            note: "Paid early with Zelle.",
          },
          {
            id: "hist-evan-2",
            date: shiftDate(-1),
            amount: 1895,
            status: "paid",
            note: "Current month settled.",
          },
        ],
      },
      {
        id: "contact-summit",
        linkedRecordId: "job-hvac",
        kind: "client",
        displayName: "Summit Dental",
        email: "ops@summitdental.com",
        phone: "(555) 918-0041",
        label: "Commercial maintenance client",
        notes: "Invoices paid net 10. Ask for front desk when arriving.",
        paymentHistory: [
          {
            id: "hist-summit-1",
            date: shiftDate(-18),
            amount: 620,
            status: "paid",
            note: "Filter replacement invoice cleared.",
          },
        ],
      },
      {
        id: "contact-hartwell",
        linkedRecordId: "job-kitchen",
        kind: "client",
        displayName: "Hartwell Design",
        email: "studio@hartwelldesign.com",
        phone: "(555) 774-2398",
        label: "Design partner",
        notes: "Wants daily photo updates until close-out.",
        paymentHistory: [
          {
            id: "hist-hartwell-1",
            date: shiftDate(-6),
            amount: 950,
            status: "paid",
            note: "Deposit received.",
          },
        ],
      },
    ],
    payments: [
      {
        id: "payment-maple-apr",
        kind: "rent",
        recordId: "property-maple",
        contactId: "contact-dana",
        label: "Maple Street April rent",
        amount: 1650,
        dueDate: shiftDate(-3),
        status: "overdue",
      },
      {
        id: "payment-cedar-apr",
        kind: "rent",
        recordId: "property-cedar",
        contactId: "contact-evan",
        label: "Cedar Avenue April rent",
        amount: 1895,
        dueDate: shiftDate(-1),
        status: "paid",
        paidAt: shiftDate(-1),
      },
      {
        id: "payment-summit",
        kind: "invoice",
        recordId: "job-hvac",
        contactId: "contact-summit",
        label: "Summit Dental service invoice",
        amount: 920,
        dueDate: shiftDate(6),
        status: "due",
      },
      {
        id: "payment-hartwell",
        kind: "invoice",
        recordId: "job-kitchen",
        contactId: "contact-hartwell",
        label: "Hartwell Design progress invoice",
        amount: 950,
        dueDate: shiftDate(-6),
        status: "paid",
        paidAt: shiftDate(-5),
      },
    ],
    tasks: [
      {
        id: "task-leak",
        mode: "landlord",
        title: "Inspect upstairs leak",
        detail: "Tenant reported a slow leak near the laundry shutoff.",
        linkedRecordId: "property-maple",
        linkedName: "1421 Maple Street, Unit 2",
        priority: "high",
        dueDate: shiftDate(1),
        notifyByPush: true,
        status: "open",
      },
      {
        id: "task-hvac",
        mode: "contractor",
        title: "Confirm rooftop access slot",
        detail: "Need building supervisor confirmation before dispatch.",
        linkedRecordId: "job-hvac",
        linkedName: "Summit Dental",
        priority: "medium",
        dueDate: shiftDate(2),
        notifyByPush: true,
        status: "in-progress",
      },
      {
        id: "task-paint",
        mode: "contractor",
        title: "Complete paint touch-up",
        detail: "Final trim pass in pantry and hall.",
        linkedRecordId: "job-kitchen",
        linkedName: "Hartwell Design",
        priority: "low",
        dueDate: shiftDate(-1),
        notifyByPush: false,
        status: "done",
      },
    ],
    expenses: [
      {
        id: "expense-heater",
        title: "Water heater shutoff kit",
        category: "Repairs",
        linkedRecordId: "property-maple",
        linkedName: "1421 Maple Street, Unit 2",
        amount: 185,
        date: shiftDate(-2),
        note: "Local plumbing supply pickup.",
      },
      {
        id: "expense-fuel",
        title: "Fuel and parking",
        category: "Travel",
        linkedRecordId: "job-hvac",
        linkedName: "Summit Dental",
        amount: 48,
        date: shiftDate(-5),
        note: "Two-site service loop.",
      },
      {
        id: "expense-lumber",
        title: "Finish lumber",
        category: "Materials",
        linkedRecordId: "job-kitchen",
        linkedName: "Hartwell Design",
        amount: 264,
        date: shiftDate(-7),
        note: "Trim replacement stock.",
      },
    ],
    activities: [
      {
        id: "activity-1",
        title: "Overdue alert sent",
        detail: "Maple Street tenant received an automated rent reminder.",
        timestamp: shiftDate(-1),
        type: "payment",
      },
      {
        id: "activity-2",
        title: "Expense logged",
        detail: "Water heater shutoff kit added under Repairs.",
        timestamp: shiftDate(-2),
        type: "expense",
      },
      {
        id: "activity-3",
        title: "Job updated",
        detail: "Summit Dental service visit moved into In Progress.",
        timestamp: shiftDate(-2),
        type: "task",
      },
      {
        id: "activity-4",
        title: "Payment received",
        detail: "Cedar Avenue rent marked paid by auto-pay.",
        timestamp: shiftDate(-3),
        type: "payment",
      },
      {
        id: "activity-5",
        title: "Property note refreshed",
        detail: "Garage keypad instructions saved for Cedar Avenue.",
        timestamp: shiftDate(-5),
        type: "record",
      },
    ],
  };
}
